on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

name: Build and Test
description: Build and test the extension on multiple platforms.

jobs:
    build:
        strategy:
            matrix:
                os: [macos-latest, ubuntu-latest, windows-latest]
        runs-on: ${{ matrix.os }}
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - uses: pnpm/action-setup@v4
              name: Install pnpm
              with:
                  version: 10.6.5
                  run_install: false

            - name: Install Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: 'pnpm'

            - name: Install dependencies
              run: pnpm install

            - name: Run tests
              run: ${{ runner.os == 'Linux' && 'xvfb-run -a npm test' || 'npm test' }}
